### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by photocyte** [Bioprotocols/container-ontology#38]
Jake mentioned the `container-ontology` was under the Apache license (https://forums.pylabrobot.org/t/database-storing-common-labware-dwps-etc-specifications/103/15), but I don't see a License.md in this repo?

**Comment by jakebeal** [comment]
It's in the setup.py, but should be made obvious via a license file.
https://github.com/Bioprotocols/container-ontology/blob/72b8b2f6af391e41032e915fa011e49df42c944c/setup.py#L37
